version: '3.1'

services:
    postgres:
        image: postgres:13.7-alpine
        container_name: typerighter-rule-manager
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=tr-rule-manager-local
            - POSTGRES_PASSWORD=tr-rule-manager-local
            - POSTGRES_DB=tr-rule-manager-local
        volumes:
            - postgres-data:/var/lib/postgresql/data
        command: [ "postgres", "-c", "log_statement=all", "-N", "500" ]
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U tr-rule-manager-local"]
          interval: 10s
          timeout: 5s
          retries: 5
    localstack:
      container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
      image: localstack/localstack:1.4.0
      ports:
        - "4566-4599:4566-4599"
        - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
      environment:
        - SERVICES=s3
        - DEBUG=true
        - DATA_DIR=/tmp/localstack/data
        - DOCKER_HOST=unix:///var/run/docker.sock
      volumes:
        - "./.tmp:/var/lib/localstack"
        - "./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
        - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
    postgres-data:
        driver: local
